spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:7778/techlabs
    username: postgres
    password: postgres




flyway:
  url: jdbc:postgresql://localhost:7778/techlabs;
  user: postgres
  password: postgres
  enabled: true
  locations:
    - 'classpath:db/migration'
